init:

  variables:
    MYSQL_DATABASE: perltest
    MYSQL_HOST: localhost
    MYSQL_USER: perltest
    MYSQL_PASSWORD: testpass
    MYSQL_ROOT_PASSWORD: ''

  services:
    mysql:
      db_name: $MYSQL_DATABASE
      db_user: $MYSQL_USER
      db_pass: $MYSQL_PASSWORD

  packages:
    mysql: {}

  script: |
    env | grep MYSQL
    zef install --/test Test::When
    cp -v t/.my.cnf ~


main:
  with-code-coverage: true
