init:

  variables:
    ALL_TESTING: 1
    
  services:
    mysql:
      db_name: perltest
      db_user: perltest
      db_pass: testpass

  packages:
    mysql: {}

  script: |
    zef install --/test Test::When
    cp -v t/.my.cnf ~


main:
  with-code-coverage: true
